version: '3.8'

services:
  servidor:
    build: 
      context: .
      dockerfile: ./servidor/Dockerfile
    container_name: linux_servidor
    hostname: servidor
    privileged: true
    tty: true
    networks:
      - red_proyecto
    volumes:
      - ./servidor_data:/data:Z 

  cliente:
    build:
      context: .
      dockerfile: ./cliente/Dockerfile
    container_name: linux_cliente
    hostname: cliente
    tty: true
    networks:
      - red_proyecto

  monitoreo:
    image: prom/prometheus:latest
    container_name: linux_monitoreo
    hostname: prometheus
    ports:
      - "9091:9090"
    networks:
      - red_proyecto

networks:
  red_proyecto:
    driver: bridge
